# === Spring-Boot ===

spring.application.name=exemplo
spring.threads.virtual.enabled=true

# === Logging ===

logging.pattern.console=[%d{dd/MM/yyyy HH:mm:ss.SSS} %clr(%t){magenta}] %clr(%-5p) %clr(%c{0}){cyan}: %m%n
logging.level.root=info
logging.level.org.springframework.web=info
logging.level.com.zaxxer.hikari=info
logging.level.br.gov.serpro=debug

# === Tomcat ===

server.servlet.context-path=/exemplo
server.tomcat.threads.max=10

# === Actuator ===

management.endpoints.web.exposure.include=*
management.info.git.enabled=true
management.info.git.mode=full

# === JPA ===

spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# === Datasource Principal ===

spring.datasource.url=jdbc:postgresql://localhost:5432/exemplo
spring.datasource.username=usrexemplosvc
spring.datasource.password=senha
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=60000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=select 1
spring.datasource.hikari.pool-name=hikari-pool-exemplo
spring.datasource.hikari.data-source-properties.ApplicationName=exemplo

# === P6Spy ===

decorator.datasource.p6spy.enable-logging=true
decorator.datasource.p6spy.multiline=true
decorator.datasource.p6spy.logging=slf4j
decorator.datasource.p6spy.log-file=spy.log

# === Integracao PF ===

exemplo.integr.pf.nome=Fulano